In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("C:\\Users\\Admin\\Desktop\\Final Project\\Data_Cleaning_done_here\\cleaned_data.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9982 entries, 0 to 9981
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     9982 non-null   str
 1   Date         9982 non-null   str
 2   Salesperson  9982 non-null   str
 3   Region       9982 non-null   str
 4   Product      9982 non-null   str
 5   Quantity     9982 non-null   float64
 6   Unit Price   9982 non-null   float64
dtypes: float64(2), str(5)
memory usage: 546.0 KB

In [4]:
df["Revenue"] = df["Quantity"] * df["Unit Price"]
df.head(20)

,Order ID,Date,Salesperson,Region,Product,Quantity,Unit Price,Revenue
0,ORD7439,2026-01-25,Nisha Kumari,North,Printer,8.0,8000.0,64000.0
1,ORD9059,2026-03-23,Bhavana Rao,East,Speakers,1.0,3000.0,3000.0
2,ORD0569,2026-01-01,Ananya Singh,South,Mouse,5.0,600.0,3000.0
3,ORD9345,2026-01-19,Shreya Ghosh,South,Headphones,7.0,2500.0,17500.0
4,ORD2237,2026-02-24,Siddharth Khanna,East,Mobile,1.0,20000.0,20000.0
5,ORD3058,2026-02-07,Siddharth Jain,North,Keyboard,7.0,1200.0,8400.0
6,ORD7507,2026-03-05,Rohan Kulkarni,North,Mobile,1.0,20000.0,20000.0
7,ORD1497,2026-02-04,Nikhil Jain,East,Mobile,9.0,20000.0,180000.0
8,ORD1796,2026-03-02,Rahul Verma,South,Monitor,7.0,12000.0,84000.0
9,ORD7854,2026-01-10,Bhavana Rao,South,Smartwatch,6.0,10000.0,60000.0
10,ORD0108,2026-03-07,Monika Sethi,South,Tablet,5.0,15000.0,75000.0
11,ORD4517,2026-01-21,Meera Nair,West,Speakers,9.0,3000.0,27000.0
12,ORD0705,2026-03-10,Shreya Das,West,Keyboard,6.0,1200.0,7200.0
13,ORD9976,2026-03-10,Kavya Rao,West,Speakers,4.0,3000.0,12000.0
14,ORD2911,2026-03-12,Rahul Choudhary,South,Speakers,3.0,3000.0,9000.0
15,ORD1651,2026-01-20,Ajay Thakur,North,External Hard Drive,7.0,5000.0,35000.0
16,ORD0312,2026-01-05,Yash Agarwal,West,Monitor,4.0,12000.0,48000.0
17,ORD9058,2026-03-03,Shreya Das,West,Smartwatch,8.0,10000.0,80000.0
18,ORD8628,2026-01-20,Pallavi Desai,West,Headphones,5.0,2500.0,12500.0
19,ORD9602,2026-03-02,Sahana Murthy,West,Speakers,2.0,3000.0,6000.0

In [5]:
df["Total Revenue"] = df["Revenue"].sum()
df.head(20)

,Order ID,Date,Salesperson,Region,Product,Quantity,Unit Price,Revenue,Total Revenue
0,ORD7439,2026-01-25,Nisha Kumari,North,Printer,8.0,8000.0,64000.0,6.571827e+08
1,ORD9059,2026-03-23,Bhavana Rao,East,Speakers,1.0,3000.0,3000.0,6.571827e+08
2,ORD0569,2026-01-01,Ananya Singh,South,Mouse,5.0,600.0,3000.0,6.571827e+08
3,ORD9345,2026-01-19,Shreya Ghosh,South,Headphones,7.0,2500.0,17500.0,6.571827e+08
4,ORD2237,2026-02-24,Siddharth Khanna,East,Mobile,1.0,20000.0,20000.0,6.571827e+08
5,ORD3058,2026-02-07,Siddharth Jain,North,Keyboard,7.0,1200.0,8400.0,6.571827e+08
6,ORD7507,2026-03-05,Rohan Kulkarni,North,Mobile,1.0,20000.0,20000.0,6.571827e+08
7,ORD1497,2026-02-04,Nikhil Jain,East,Mobile,9.0,20000.0,180000.0,6.571827e+08
8,ORD1796,2026-03-02,Rahul Verma,South,Monitor,7.0,12000.0,84000.0,6.571827e+08
9,ORD7854,2026-01-10,Bhavana Rao,South,Smartwatch,6.0,10000.0,60000.0,6.571827e+08
10,ORD0108,2026-03-07,Monika Sethi,South,Tablet,5.0,15000.0,75000.0,6.571827e+08
11,ORD4517,2026-01-21,Meera Nair,West,Speakers,9.0,3000.0,27000.0,6.571827e+08
12,ORD0705,2026-03-10,Shreya Das,West,Keyboard,6.0,1200.0,7200.0,6.571827e+08
13,ORD9976,2026-03-10,Kavya Rao,West,Speakers,4.0,3000.0,12000.0,6.571827e+08
14,ORD2911,2026-03-12,Rahul Choudhary,South,Speakers,3.0,3000.0,9000.0,6.571827e+08
15,ORD1651,2026-01-20,Ajay Thakur,North,External Hard Drive,7.0,5000.0,35000.0,6.571827e+08
16,ORD0312,2026-01-05,Yash Agarwal,West,Monitor,4.0,12000.0,48000.0,6.571827e+08
17,ORD9058,2026-03-03,Shreya Das,West,Smartwatch,8.0,10000.0,80000.0,6.571827e+08
18,ORD8628,2026-01-20,Pallavi Desai,West,Headphones,5.0,2500.0,12500.0,6.571827e+08
19,ORD9602,2026-03-02,Sahana Murthy,West,Speakers,2.0,3000.0,6000.0,6.571827e+08

In [ ]:
df.to_csv("C:\\Users\\Admin\\Desktop\\Final Project\\Report_generation\\data_with_revenue.csv", index=False)