In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\Admin\\Desktop\\Final Project\\Report_generation\\data_with_revenue.csv")

In [3]:
df["Revenue"] = df["Quantity"] * df["Unit Price"]
df.head()

,Order ID,Date,Salesperson,Region,Product,Quantity,Unit Price,Revenue,Total Revenue
0,ORD7439,2026-01-25,Nisha Kumari,North,Printer,8.0,8000.0,64000.0,6.571827e+08
1,ORD9059,2026-03-23,Bhavana Rao,East,Speakers,1.0,3000.0,3000.0,6.571827e+08
2,ORD0569,2026-01-01,Ananya Singh,South,Mouse,5.0,600.0,3000.0,6.571827e+08
3,ORD9345,2026-01-19,Shreya Ghosh,South,Headphones,7.0,2500.0,17500.0,6.571827e+08
4,ORD2237,2026-02-24,Siddharth Khanna,East,Mobile,1.0,20000.0,20000.0,6.571827e+08

In [ ]:
# Summarize sales by region
region_summary = df.groupby("Region").agg(
    Total_Revenue=("Revenue", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Total_Orders=("Order ID", "nunique")
).reset_index()
region_summary.head()

    Region  Total_Revenue  Total_Quantity  Total_Orders
0   south    3.510000e+05       18.000000             3
1     East   1.659312e+08    14233.637648          2536
2    North   1.636846e+08    13783.091765          2515
3    South   1.598430e+08    13250.000000          2394
4     West   1.673729e+08    14068.000000          2534

In [8]:
# Sort by revenue from highest to lowest
region_summary = region_summary.sort_values(
    by="Total_Revenue", ascending=False
)
region_summary.head(3)

  Region  Total_Revenue  Total_Quantity  Total_Orders
4   West   1.673729e+08    14068.000000          2534
1   East   1.659312e+08    14233.637648          2536
2  North   1.636846e+08    13783.091765          2515

In [7]:
# Display the summary
print(region_summary.to_string(index=False))

 Region  Total_Revenue  Total_Quantity  Total_Orders
   West   1.673729e+08    14068.000000          2534
   East   1.659312e+08    14233.637648          2536
  North   1.636846e+08    13783.091765          2515
  South   1.598430e+08    13250.000000          2394
 south    3.510000e+05       18.000000             3